### ISSUE TITLE
Rejestracja nie działa

### ISSUE THREAD

**Issue by PerzotProgrammer** [MiloszMichalak/WanderView#1]
Dzień dobry,
chciałem dzisiaj się zarejestrować z nowego konta, lecz po naciśnięciu przycisku nic się nie działo.
Sprzęt:
- Pixel 9 Pro XL (Emulowany w Android Studio API 34)
- Wander View z commitu 34a4e1ed97619b416e8de668bc8cbb21d57a615c

Proszę o szybką naprawę, ponieważ aplikacja jest nieużywalna!

**Comment by MiloszMichalak** [comment]
Błąd naprawiony, przyczyna były błędne permisje w bazie danych
