### ISSUE TITLE
Brak możliwości użycia aplikacji w orientacji horyzontalnej

### ISSUE THREAD

**Issue by PerzotProgrammer** [MiloszMichalak/WanderView#2]
Dzień dobry,
chciałem skorzystać z aplikacji podczas leżenia w łóżku, obróciłem telefon horyzontalnie i nie mogłem używać ekranu rejestracji (który dodatkowo nie działał).
Sprzęt:
- Pixel 9 Pro XL (Emulowany w Android Studio API 34 (nie, nie leżałem w łóżku))
- Wander View z commitu 34a4e1ed97619b416e8de668bc8cbb21d57a615c

Proszę o szybką naprawę, ponieważ aplikacja jest nieużywalna!

**Comment by MiloszMichalak** [comment]
Dzień dobry, 
Issue zostało naprawione na poziomie devu, w najbliższym commicie widoki zostały przystosowane do orientacji horyzontalnej oraz aplikacja nada się do użytku
